routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'blog');

//grupo de rutas para el control de autenticación
/*Route::get('/', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@Login')->name('login');
Route::get('logout', 'Auth\LoginController@Logout')->name('logout');*/
Auth::routes();

//web
Route::get('blog', 'Web\PageController@blog')->name('blog');
Route::get('entrada/{slug}', 'Web\PageController@post')->name('post');
Route::get('category/{slug}', 'Web\PageController@category')->name('category');
Route::get('etiqueta/{slug}', 'Web\PageController@tag')->name('tag');

//admin
Route::resource('tags',       'Admin\TagController');
Route::resource('categories', 'Admin\CategoryController');
Route::resource('posts',      'Admin\PostController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'slug', 'body'
    ];

    public function posts() {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
Use App\Http\Requests\CategoryStoreRequest;
Use App\Http\Requests\CategoryUpdateeRequest;
use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id', 'DESC')->paginate();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $categories = Category::create($request->all());

        return redirect()->route('categories.edit', $categories->id)
                ->with('info', 'Categoria creada con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::find($id);

        return view('admin.category.show', compact('categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::find($id);

        return view('admin.category.edit', compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateeRequest $request, $id)
    {
        $categories = Category::find($id);

        $categories->fill($request->all())->save();
        return redirect()->route('categories.edit', $categories->id)
                ->with('info', 'Categoria actualizada con éxito');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return back()->with('info', 'Eliminado correctamente');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Crear Categoria

                </div>

                <div class="panel-body">
                    {!! Form::open(['route' => 'categories.store'])!!}

                        @include('admin.category.partials.form')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Editar Categoria

                </div>

                <div class="panel-body">
                   {!! Form::model($categories, ['route' => ['categories.update', $categories->id], 'method' => 'PUT'])!!}

                        @include('admin.category.partials.form')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Lista de Categoria
                    <a href=" {{ route('categories.create')}}" class="btn btn-sm btn-primary pull-right">
                        Crear
                    </a>
                </div>

                <div class="panel-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th width="10px">ID</th>
                                <th>Nombre</th>
                                <th colspan="3">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td width="10px">
                                        <a href=" {{route('categories.show', $category->id)}} " class="btn btn-sm btn-default">
                                            ver
                                        </a>
                                    </td>
                                    <td width="10px">
                                        <a href=" {{route('categories.edit', $category->id)}} " class="btn btn-sm btn-default">
                                            editar
                                        </a>
                                    </td>
                                    <td width="10px">
                                            {!! Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'DELETE']) !!}
                                                <button class="btn btn-sm btn-danger">
                                                    Eliminar
                                                </button>
                                            {!! Form::close() !!}

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $categories->render()}}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/category/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Ver Categoria

                </div>

                <div class="panel-body">
                    <p><strong>Nombre</strong> {{$categories->name}}</p>
                    <p><strong>Slug</strong> {{$categories->slug}}</p>
                    <p><strong>Contenido</strong> {{$categories->body}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection